# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vdag_service.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12vdag_service.proto\"3\n\x0cvDAGFileInfo\x12\x10\n\x08metadata\x18\x01 \x01(\t\x12\x11\n\tfile_data\x18\x02 \x01(\x0c\"\x84\x01\n\x13vDAGInferencePacket\x12\x12\n\nsession_id\x18\x03 \x01(\t\x12\x0e\n\x06seq_no\x18\x04 \x01(\x04\x12\x11\n\tframe_ptr\x18\x05 \x01(\x0c\x12\x0c\n\x04\x64\x61ta\x18\x06 \x01(\t\x12\n\n\x02ts\x18\x08 \x01(\x01\x12\x1c\n\x05\x66iles\x18\t \x03(\x0b\x32\r.vDAGFileInfo2K\n\x14vDAGInferenceService\x12\x33\n\x05infer\x12\x14.vDAGInferencePacket\x1a\x14.vDAGInferencePacketb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vdag_service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_VDAGFILEINFO']._serialized_start=22
  _globals['_VDAGFILEINFO']._serialized_end=73
  _globals['_VDAGINFERENCEPACKET']._serialized_start=76
  _globals['_VDAGINFERENCEPACKET']._serialized_end=208
  _globals['_VDAGINFERENCESERVICE']._serialized_start=210
  _globals['_VDAGINFERENCESERVICE']._serialized_end=285
# @@protoc_insertion_point(module_scope)
