# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\"x\n\nAIOSPacket\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x0e\n\x06seq_no\x18\x02 \x01(\x04\x12\x0c\n\x04\x64\x61ta\x18\x04 \x01(\t\x12\n\n\x02ts\x18\x05 \x01(\x01\x12\x12\n\noutput_ptr\x18\x06 \x01(\t\x12\x18\n\x05\x66iles\x18\x07 \x03(\x0b\x32\t.FileInfo\"/\n\x08\x46ileInfo\x12\x10\n\x08metadata\x18\x01 \x01(\t\x12\x11\n\tfile_data\x18\x02 \x01(\x0c\"\xc1\x01\n\x14\x42lockInferencePacket\x12\x10\n\x08\x62lock_id\x18\x01 \x01(\t\x12\x12\n\nsession_id\x18\x03 \x01(\t\x12\x0e\n\x06seq_no\x18\x04 \x01(\x04\x12\x11\n\tframe_ptr\x18\x05 \x01(\x0c\x12\x0c\n\x04\x64\x61ta\x18\x06 \x01(\t\x12\x18\n\x10query_parameters\x18\x07 \x01(\t\x12\n\n\x02ts\x18\x08 \x01(\x01\x12\x18\n\x05\x66iles\x18\t \x03(\x0b\x32\t.FileInfo\x12\x12\n\noutput_ptr\x18\n \x01(\t2D\n\x15\x42lockInferenceService\x12+\n\x05infer\x12\x15.BlockInferencePacket\x1a\x0b.AIOSPacketb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_AIOSPACKET']._serialized_start=17
  _globals['_AIOSPACKET']._serialized_end=137
  _globals['_FILEINFO']._serialized_start=139
  _globals['_FILEINFO']._serialized_end=186
  _globals['_BLOCKINFERENCEPACKET']._serialized_start=189
  _globals['_BLOCKINFERENCEPACKET']._serialized_end=382
  _globals['_BLOCKINFERENCESERVICE']._serialized_start=384
  _globals['_BLOCKINFERENCESERVICE']._serialized_end=452
# @@protoc_insertion_point(module_scope)
